repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.3.3post1
    hooks:
    -   id: pre-commit-update
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.370
    hooks:
    -   id: pyright
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
    -   id: ruff
        args:
        -   --fix
    -   id: ruff-format
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
    -   id: vulture
        args:
        -   ./
        -   --exclude
        -   '*/.venv/*'
        -   --ignore-names
        -   _generate_next_value_
-   repo: local
    hooks:
    -   id: coverage
        entry: just coverage
        language: system
        name: coverage
        pass_filenames: false
        args:
        -   --fail-under
        -   '50'
-   repo: https://github.com/pdm-project/pdm
    rev: 2.16.1
    hooks:
    -   id: pdm-export
        files: ^pdm.lock$
        args:
        -   -o
        -   requirements.txt
        -   --without-hashes
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
    -   id: markdownlint-fix
