[package]
name = "tsu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bat = "0.26.1"
chrono = "0.4.39"
clap = { version = "4.5.31", features = ["derive", "string"] }
colored = "3.0.0"
cron = { version = "0.16.0", features = ["serde"] }
cron-descriptor = "0.1.1"
dirs = "6.0.0"
english-to-cron = "0.1.2"
figment = { version = "0.10.19", features = ["env", "toml"] }
home = "0.5.11"
path-dedot = "3.1.1"
plist = "1.7.0"
serde = { version = "1.0.217", features = ["derive"] }
shellexpand = "3.1.0"
symphonia = { version = "0.5.4", features = ["all-codecs", "all-formats"] }
symphonia-core = "0.5.4"
toml = "1.0.1"
walkdir = "2.5.0"
