branch_whitelist = []
disable_bump_commit = false
disable_changelog = false
from_latest_tag = false
generate_mono_repository_global_tag = true
ignore_merge_commits = true
post_bump_hooks = []
post_package_bump_hooks = []
pre_bump_hooks = []
pre_package_bump_hooks = []
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"

[bump_profiles]

[changelog]
owner = ""
path = "CHANGELOG.md"
remote = ""
repository = ""
template = "remote"

[[changelog.authors]]
signature = ""
username = ""

[commit_types]

[git_hooks]

[packages]
