#!/usr/bin/env bash

if ! command -v "brew" &>/dev/null; then
    curl -fsSL \
        "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
fi

brew bundle --no-upgrade --file Brewfile.prod
