[tool.poetry]
name = "musicbros"
version = "0.2.0"
description = "CLI for managing the 'Musicbros' audio file archive"
authors = ["Ben Rosen <benjamin.j.rosen@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
musicbros = "musicbros.main:app"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
typer = {extras = ["all"], version = "^0.4.0"}
tinytag = "^1.6.0"
beets = "^1.5.0"
click = "8.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.10b0"
isort = "^5.10.0"
pre-commit = "^2.15.0"
pyproject-flake8 = "^0.0.1-alpha.2"
pyinstaller = "^4.10"
bpython = "^0.22.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
experimental_string_processing = true

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"
