[tool.poetry]
name = "tsundeoku"
version = "0.5.0"
description = 'CLI for managing imports from a shared folder to a "beets" library'
authors = ["Ben Rosen <benjamin.j.rosen@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
tsundeoku = "tsundeoku.main:tsundeoku"

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.6.1"}
tinytag = "^1.8.1"
beets = "^1.6.0"
click = "^8.1.3"
pydantic = "^1.10.1"
rtoml = "^0.8.0"
tomli = "^2.0.1"
tomli-w = "^1.0.0"
xmltodict = "^0.13.0"
yagmail = "^0.15.285"
pync = "^2.0.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pre-commit = "^2.20.0"
coverage = "^6.4.4"
bpython = "^0.23"

[tool.poetry.group.dev.dependencies]
pytest-mock = "^3.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
preview = true
line-length = 79

[tool.flake8]
extend-ignore = "E203"
