set working-directory := "../.."

# View help text
@help *args:
    .environments/git/scripts/help.nu {{ args }}

# Check for leaked secrets
@leaks *args:
    .environments/git/scripts/leaks.nu {{ args }}
