set working-directory := "../.."

# View help text
@help *args:
    .environments/nix/scripts/help.nu {{ args }}

# Format nix files
@format *args:
    .environments/nix/scripts/format.nu {{ args }}

# Lint nix files
@lint *args:
    .environments/nix/scripts/lint.nu {{ args }}

# Open an interactive nix shell
@shell *args:
    .environments/nix/scripts/shell.nu {{ args }}

alias sh := shell
